# Generated by Django 5.1.1 on 2024-09-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('price', models.IntegerField()),
                ('pack_category', models.CharField(max_length=36)),
                ('level_category', models.CharField(max_length=36)),
                ('description', models.TextField()),
            ],
        ),
    ]
